// <auto-generated />
using System;
using Entity_Framework_Platzi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework_Platzi.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230226020336_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Framework_Platzi.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("f32d1ab5-64a4-4df0-8e82-8326fcd8bdcd"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("28a8f77b-ca15-4f4f-900e-2de94d3c2260"),
                            Nombre = "Actividades personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("Entity_Framework_Platzi.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("0559da4f-e287-4412-bb0e-1ef3648a8b1f"),
                            CategoriaId = new Guid("f32d1ab5-64a4-4df0-8e82-8326fcd8bdcd"),
                            FechaCreacion = new DateTime(2023, 2, 25, 23, 3, 36, 104, DateTimeKind.Local).AddTicks(9686),
                            PrioridadTarea = 1,
                            Titulo = "Pagar Telecentro"
                        },
                        new
                        {
                            TareaId = new Guid("8cea31e3-1bba-46e7-9195-b595479625fd"),
                            CategoriaId = new Guid("28a8f77b-ca15-4f4f-900e-2de94d3c2260"),
                            FechaCreacion = new DateTime(2023, 2, 25, 23, 3, 36, 104, DateTimeKind.Local).AddTicks(9701),
                            PrioridadTarea = 0,
                            Titulo = "Digitar tango"
                        });
                });

            modelBuilder.Entity("Entity_Framework_Platzi.Models.Tarea", b =>
                {
                    b.HasOne("Entity_Framework_Platzi.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Entity_Framework_Platzi.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
